server:
  port: 8099

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 数据库配置；启动时配置数据库资源信息
spring:
  datasource:
    mysql:
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/ai-agent-station_01?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        pool-name: Retail_HikariCP
        minimum-idle: 15 #最小空闲连接数量
        idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
        maximum-pool-size: 25 #连接池最大连接数，默认是10
        auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
        max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
        connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
        connection-test-query: SELECT 1
    pgvector:
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: postgres
      url: jdbc:postgresql://117.72.214.115:15432/ai-rag-knowledge
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maximum-pool-size: 5
        minimum-idle: 2
        idle-timeout: 30000
        connection-timeout: 30000
  ai:
    openai:
      base-url: https://apis.itedus.cn
      api-key: sk-qfxpzhJb6UTCdIzf2d7fE9E52e4c497aB9CfA550128f07D0
    agent:
      auto-config:
        enabled: true
#        client-ids: 4101,4102,4103,4104
        client-ids: 3101,3102,3103,3104,4101,4102,4103,4104

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml